name: k008
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo x > x.txt
      - uses: actions/upload-artifact@v4
        with: {name: package, path: x.txt}
      - uses: actions/download-artifact@v4
        with: {name: package}
